### ISSUE TITLE
migrationRules.js is hard coded and not picking up different three versions

### ISSUE THREAD

**Issue by jjwall** [fairygui/FairyGUI-threejs#25]
Hello the migrationRules.js files is hard coded for versions 116 and 134. I recommend deprecating three.js versions earlier than 0.134.0 and changing the code base to use .invert() and .copy($1).invert() where .inverse() and .getInverse() is being used.

**Comment by xiaoguzhu** [comment]
fix https://github.com/fairygui/FairyGUI-threejs/commit/3ea188c1a7b49557fdf413277df3702798303d10
