### ISSUE TITLE
fairygui-threejs 中要唤起手机相册有实现方法吗

### ISSUE THREAD

**Issue by shiftbank** [fairygui/FairyGUI-threejs#28]
一般在js 和html中实现唤起手机相机直接用html的 input标签，type="file" accept="image/*"  即可
但目前fairygui 官网写 富文本支持 html， 
仅支持  INPUT 支持显示以下语法：
    //显示一个按钮
    <input type='button' value='标题'/>
    //显示一个输入框
    <input type='text' value='文本内容'/>

是不支持 
    <input type="file" accept="image/*" /> 吗

https://www.fairygui.com/docs/editor/richtext

单独写一个 html覆盖 fairygui-three的canvas，无法唤起相机，应该是click事件还没传到input标签就被捕获了

**Comment by xiaoguzhu** [comment]
这个需求与这个库无关
