### ISSUE TITLE
three 150版本里各种报错，请修复更新一下

### ISSUE THREAD

**Issue by pxim** [fairygui/FairyGUI-threejs#30]
three 150版本里各种报错，请修复更新一下

![image](https://user-images.githubusercontent.com/5111701/234517267-77ee3f60-6fe0-4da9-8b08-acfe27a0a158.png)

**Comment by xiaoguzhu** [comment]
fix https://github.com/fairygui/FairyGUI-threejs/commit/3ea188c1a7b49557fdf413277df3702798303d10
